# Generated by Django 5.2.1 on 2025-08-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_like_count_house_share_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(upload_to='house_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
