# Generated by Django 5.2.1 on 2025-09-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_houseimage_image_alter_houseimage_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
