# Generated by Django 5.2.1 on 2025-09-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_house_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Houses'},
        ),
        migrations.RenameField(
            model_name='house',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
