# Generated by Django 5.2.1 on 2025-09-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
