# Generated by Django 5.2.1 on 2025-09-15 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='created_at',
        ),
    ]
