# Generated by Django 5.2.1 on 2025-09-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_remove_vehicle_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
