# Generated by Django 5.2.1 on 2025-08-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_remove_product_image_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
