# Generated by Django 5.2.1 on 2025-08-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0003_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
