# Generated by Django 5.2.1 on 2025-08-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0004_product_like_count_product_share_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
