# Generated by Django 5.2.1 on 2025-09-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='item',
        ),
        migrations.AddField(
            model_name='conversation',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='object_id',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
