# Generated by Django 5.2.1 on 2025-08-29 17:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryitems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('specialty', models.CharField(choices=[('disease', 'Disease Management'), ('nutrition', 'Nutrition & Feed'), ('prevention', 'Biosecurity & Prevention'), ('breeding', 'Breeding & Genetics'), ('general', 'General Practice')], max_length=20)),
                ('languages', models.CharField(help_text='Comma-separated list of languages', max_length=200)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('availability', models.CharField(choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('all_week', 'All Week'), ('emergency', '24/7 Emergency')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Consultation'), ('visit', 'Farm Visit'), ('analysis', 'Feed Analysis'), ('assessment', 'Farm Assessment')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.CharField(blank=True, help_text='e.g., 1 hour, per visit', max_length=50)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='poultryitems.consultant')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultryitems.consultant')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultryitems.consultationservice')),
            ],
        ),
    ]
