# Generated by Django 5.2.1 on 2025-08-29 17:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryitems', '0002_consultant_consultationservice_consultationbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('egg_type', models.CharField(choices=[('organic', 'Organic'), ('free_range', 'Free Range'), ('cage_free', 'Cage Free'), ('conventional', 'Conventional'), ('pasture_raised', 'Pasture Raised')], default='conventional', max_length=20)),
                ('certification', models.CharField(choices=[('none', 'None'), ('usda_organic', 'USDA Organic'), ('non_gmo', 'Non-GMO Project Verified'), ('animal_welfare', 'Animal Welfare Approved'), ('local', 'Local Farm Certified')], default='none', max_length=20)),
                ('quantity_available', models.PositiveIntegerField(help_text='Number of eggs currently available')),
                ('price_per_dozen', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_order_quantity', models.PositiveIntegerField(default=1, help_text='Minimum dozen required for order')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Egg Seller',
                'verbose_name_plural': 'Egg Sellers',
                'ordering': ['-is_verified', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='EggOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField()),
                ('quantity', models.PositiveIntegerField(help_text='Number of dozens ordered')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('preferred_delivery_date', models.DateField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='poultryitems.eggseller')),
            ],
        ),
    ]
