# Generated by Django 5.2.1 on 2025-09-01 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryitems', '0003_eggseller_eggorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=200, verbose_name='Farm Name')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('available_quantity', models.PositiveIntegerField(verbose_name='Available Chickens')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Minimum Price')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Maximum Price')),
                ('breeds', models.CharField(max_length=300, verbose_name='Breeds')),
                ('description', models.TextField(verbose_name='Description')),
                ('delivery_available', models.BooleanField(default=False, verbose_name='Delivery Available')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Vaccinated')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('telegram_handle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Handle')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number')),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram Handle')),
                ('youtube_channel', models.URLField(blank=True, null=True, verbose_name='YouTube Channel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chicken_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chicken Seller',
                'verbose_name_plural': 'Chicken Sellers',
                'ordering': ['-created_at'],
            },
        ),
    ]
