# Generated by Django 5.2.1 on 2025-09-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryitems', '0004_chickenseller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
