# Generated by Django 5.2.1 on 2025-09-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryitems', '0005_alter_item_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('program', models.CharField(choices=[('meat_chickens', 'Meat Chickens'), ('layer_chickens', 'Layer Chickens'), ('dual_purpose_chickens', 'Dual Purpose Chickens')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
